export enum CONTACTTYPE {
  CUSTOMER = 'CUSTOMER',

  KITCHEN = 'KITCHEN',

  NUTRITIONIST = 'NUTRITIONIST',

  LOGISTIC = 'LOGISTIC',

  OUTSOURCE = 'OUTSOURCE',

  PARTHNER = 'PARTHNER',

  SUBCONTRACTOR = 'SUBCONTRACTOR',

  EMPLOYEE = 'EMPLOYEE',
}
